language: go
install: true
go:
- '1.12'
script:
- "./build.sh -n -u -l -w -t"
notifications:
  email:
    recipients:
    - morfien101@gmail.com
    on_success: change
    on_failure: always
env:
  global:
  - GO111MODULE=on
  - secure: "H8eqSStQdkbjiwUhTFH4HEdhFSe3vL6dpetXZTYfLJ7R7MNPiIQ9J57EHctTEZIOxTivMTbvfgz61ItMin1tYgH8rt2/y7jLBLwaL5E1G8q6/YIaYhJDtmHGMYpmPZmm5NBll13m6Atn2UZlQmAnBhW1rj1lC+0lAOjLlBKYjCCD9HE51+t6ENaIBdQ9wrVFkvBryWXDn+FwDo07N0DqRgKC4oJLSsVsfPqkktjuJsNCPnzte6rAMd2A2a+4hXOGQT95Eo0Nos5af5LmHLjFCPoOhiT0QnlbydmrEWJxhfW5Ydfu70feyRO0MmmEXmLJDF1w0mHM2FO1kSwLwpT90y6cgbOPH0JtS44ZBQNH1DMpgZIEapkoVzxmNIFyxxsS7U47k3V2HQ1mwVxiQt54KZOdgrEwUbI1FfUAClZEn+ogwbE4ybHQgOVMy6mQ5hqWpWvVr0nRwzzVDHNPYR2DK8EZo9HTgndvnp+YYAh7HenLmo1t15x2LWQBG/Hqag2EKIhEd5N8BDJA6dW00VnVfnCh//SeIEWt2IqW50bY6EtTIeMzR1Q1tCaqJab2yKu9M8fDJwJQVk8S/5VShmz78hXcqw6Y9Jg0i6BTtLOWklb3bpNF/lKbzZygjObJ80hc8KeqtWKvn3A+AUs/NnS1/tabifzPOmmgKJrutPcQcgQ="
branches:
  only:
  - master
  except:
  - "/\\+travis\\d+$/"
before_deploy:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- cp -v artifacts/*.tar.gz artifacts/*.zip $PUBDIR
- git config --local user.name "Travis"
- git config --local user.email "morfien101@gmail.com"
- git tag "$(./build.sh -v)" --force
deploy:
  provider: releases
  api_key:
    secure: laeVnjDBGHbcqP51yuaegNPzVFVw5cgsU/DD4YGSvbY1aec+v80pk/m+7gy+DP42f9s4Blq4EteKY/lUPFkvIbUKL45+y4r3pkyMbiZguRDgEIwA1GpEJKHTW4JZV0Gjyo3o1phzGolugws3pso65pDMKVoCb6X4K6Lc/L/Oufckjik5VaHJa5IffS72Gjwn/yUNDMPGqrr/2pCjlyOPeC4Jl+GIo0rSGp8+J3tLleDwwDtHntYshKiwfBIkmjp3YqDgtOIEoGovxlFX8qtpjRPK3juteRo4nblINFKgkiMBpJ1DKOjmsNw1TDdFh8PVABtRq4nWt1X8+nUS01n61HSb/DxUTtaQohuyLWXDWxFmD+Ro1AJkWS8SOL2w9hP/l/zhyoyggsQJlWj9lJ8cjEfGf8RUNHzWX7C7UkROQMJrQEJHp6m9GExKUNVOVLlF5NzWuAx1waCM9L85To+afj2W8FT+xeh46LpKb9zLvkILSm85tpw7mj3kZcno6RKlQkGP9p2293RuEOXx/V/26+JMG1Fizs+kD/QD4sKnY0cSSdZfR+cEM7S8kSjt/qeNXo6bfljAq1g6RfgW/pRfg2qlC4OrsD8Zm9NxMwnuSDlFrum7+lPR/meEB7jTsfHuRNlUKWRXFIO4Ko5UDI69QUkn9nuUJzEtt3bc3FE+yZo=
  file: $PUBDIR/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: morfien101/go-parameterStoreReader
