language: go
install: true
go:
- '1.12'
script:
- "./build.sh -n -u -l -w"
notifications:
  email:
    recipients:
    - morfien101@gmail.com
    on_success: change
    on_failure: always
env:
  global:
  - GO111MODULE=on
  - secure: Pha3EY1cTvCaJwUjLVX2cv0rIoOaFZ7ktjKLqvVSzX1aDy2AdJ1NefsK5n5o8xFQ8zfQj+tyYM7TaLe1XZjlMZgWyJCmoaFkLXGs5tvuaAWUBiyXpX4Zbv/QTS0qP5ydmxMihe+PRL9Mtm+mitgpEyiMrfVzF/6vcGweyy/5CNQVe6bNN5fitsDfLBWMVGSLDdV3fJm3VHmcYUhowU6Soo0vyMkvoqpp1G51eOKZVLcZJMBwuXbxQAlXc0KERVF69h6Fpqy7ScJ2d29pZRjn/Bb0HsqGnEAAPYllt85wjH4nedpPn6U/b9ZMvybK27xzHUBtEnh9NjbLna/IDR/p9xhVjc+cLTNvkPiVn/XtQ5lHrwrcR34whWtZPZW/4ho6t/KBno5OJpfHPzb2ILQEszsAVNPKo3DXoFMZ4KTSn9G39uErLtZ1KK9UrXr97L4G+IewxztXh/PKTYkqMp1dGSzOom8L14I4a2u3SrXQ7DLddSu4J31lr8XpZLeNjtNrA9xr7RJRMriep5OAmSQlXmxmj6mf9GkkMGNrJK74csxXUPpnx5F2oj5Ug9KXyFmNaPpI8dIWyTZS7ax66laVS94PFyugoDq8mojnvQ3Z7gWntdyjRYketeDqPXOqbEPSGbpg1LFxtmkHfNB5Y3526yKAPPEGJ6xCYgAmjWLWD7A=
branches:
  only:
  - master
  except:
  - "/\\+travis\\d+$/"
before_deploy:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- cp -v artifacts/*.tar.gz artifacts/*.zip $PUBDIR
- git config --local user.name "Travis"
- git config --local user.email "morfien101@gmail.com"
- git tag "$(./build.sh -v)" --force
deploy:
  provider: releases
  api_key:
    secure: laeVnjDBGHbcqP51yuaegNPzVFVw5cgsU/DD4YGSvbY1aec+v80pk/m+7gy+DP42f9s4Blq4EteKY/lUPFkvIbUKL45+y4r3pkyMbiZguRDgEIwA1GpEJKHTW4JZV0Gjyo3o1phzGolugws3pso65pDMKVoCb6X4K6Lc/L/Oufckjik5VaHJa5IffS72Gjwn/yUNDMPGqrr/2pCjlyOPeC4Jl+GIo0rSGp8+J3tLleDwwDtHntYshKiwfBIkmjp3YqDgtOIEoGovxlFX8qtpjRPK3juteRo4nblINFKgkiMBpJ1DKOjmsNw1TDdFh8PVABtRq4nWt1X8+nUS01n61HSb/DxUTtaQohuyLWXDWxFmD+Ro1AJkWS8SOL2w9hP/l/zhyoyggsQJlWj9lJ8cjEfGf8RUNHzWX7C7UkROQMJrQEJHp6m9GExKUNVOVLlF5NzWuAx1waCM9L85To+afj2W8FT+xeh46LpKb9zLvkILSm85tpw7mj3kZcno6RKlQkGP9p2293RuEOXx/V/26+JMG1Fizs+kD/QD4sKnY0cSSdZfR+cEM7S8kSjt/qeNXo6bfljAq1g6RfgW/pRfg2qlC4OrsD8Zm9NxMwnuSDlFrum7+lPR/meEB7jTsfHuRNlUKWRXFIO4Ko5UDI69QUkn9nuUJzEtt3bc3FE+yZo=
  file: $PUBDIR/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: morfien101/go-parameterStoreReader
